version: '3'
#command: redis-server --save "" --appendonly no
services:
  redis:
    image: redis
    networks:
      - net

  saver:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.saver
    env_file:
      - ../env/env.txt
    volumes:
      - ~/webarchive:/app/webarchive
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.0'
          memory: '0'
    networks:
      - net

  url_grabber:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.grabber
    env_file:
      - ../env/env.txt
    depends_on:
      - redis
    networks:
      - net

  notificator:
    build:
      context: ..
      dockerfile: ./docker/Docker.notificator
    env_file:
      - ../env/env.txt
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge